---
- name: Testing andrewrothstein.kubic
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Installing buildah and podman
      become: true
      become_user: root
      ansible.builtin.package:
        name:
          - buildah
          - podman
        state: present
