---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: installing buildah and podman
      become: true
      become_user: root
      package:
        name:
          - buildah
          - podman
        state: present
